anti:
  reptile:
    manager:
      enabled: true
      ip-rule:
        enabled: true
        request-max-size: 10
        expiration-time: 20000000
      ua-rule:
        enabled: true
        allowed-mobile: true
        allowed-pc: true

spring:
  redis:
    host: localhost
    port: 6379
    database: 12
    password: password
    timeout: 10000
    pool:
      #  连接池最大连接数（使用负值表示没有限制）
      max-active: 2000
      #  连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      #  连接池中的最大空闲连接
      max-idle: 500
      #  连接池中的最小空闲连接
      min-idle: 0
    redisson:
      file: classpath:redisson.yml
